/* Exp 3 — Dynamic Orbit Topology with Real ISL + B2 + Throughput
 * Reads topology events from XML/JSON generated by orbit-events.py.
 * Pre-builds all possible links, enables/disables per event, monitors via queue.
 */
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/sbdp-header.h"
#include "ns3/packet-sink-helper.h"
#include "ns3/on-off-helper.h"
#include <map><vector><set><sstream><cstring><fstream>
using namespace ns3;
NS_LOG_COMPONENT_DEFINE("SbdpOrbit");

// ═══════════ SatRouter — same as Exp 2 (queue monitoring + B2) ═══════════
class SatRouter : public Application {
public:
  static TypeId GetTypeId(); SatRouter(){}
  void SetBw(double in,double out){m_in=in;m_out=out;}
  void AddNb(std::string n,Ipv4Address ip,double bw){m_nb[n]={ip,bw};}
  void AddDirectGs(std::string g,double bw){m_gsDirect[g]=bw;m_gs[g]=bw;m_bestGs=g;m_bestBw=bw;m_nexthop[g]="";}
  void SetRoute(std::string gs,std::string nb){m_nexthop[gs]=nb;}
  Ipv4Address GetNbIp(const std::string&n)const{auto it=m_nb.find(n);return it!=m_nb.end()?it->second.ip:Ipv4Address::GetAny();}
  void InstallMonitor(std::string nbName,Ptr<NetDevice> dev);
  void UpdateBest(){m_bestBw=0;for(auto&p:m_gs)if(p.second>m_bestBw){m_bestBw=p.second;m_bestGs=p.first;}}
  double GetBestE2e()const{return m_bestBw>0?m_bestBw:GetLocalBw();}
  std::string GetBestGs()const{return m_bestGs;}
  double GetLocalBw()const{double b=m_out;if(m_in>0&&m_in<b)b=m_in;return b;}
  std::map<std::string,double>m_gs;
  std::map<std::string,std::string>m_nexthop;
  struct Nb{Ipv4Address ip;double bw;};
  struct NbMon{Ptr<DropTailQueue<Packet>>queue;uint64_t lastBytes=0;double availBw=0;};
  std::map<std::string,Nb>m_nb;
  std::map<std::string,NbMon>m_nbMon;
private:
  virtual void StartApplication()override;virtual void StopApplication()override;
  void RecvN2(Ptr<Socket>s);void RecvEx(Ptr<Socket>s);
  void SendPush();void SendRequest();void SendReply(const std::string&);void CheckPortChange();
  Ptr<Socket>m_n2sk,m_sk;double m_in=0,m_out=0,m_bestBw=0;std::string m_bestGs;
  std::map<std::string,double>m_gsDirect,m_nbSnapshot;
  double m_lastMonTime=0;EventId m_ct;bool m_init=false;uint16_t m_seq=0;
};
NS_OBJECT_ENSURE_REGISTERED(SatRouter);
TypeId SatRouter::GetTypeId(){static TypeId tid=TypeId("ns3::SatRouter").SetParent<Application>().SetGroupName("Sbdp").AddConstructor<SatRouter>();return tid;}
void SatRouter::InstallMonitor(std::string nbName,Ptr<NetDevice> dev){
  auto p2p=DynamicCast<PointToPointNetDevice>(dev);auto&m=m_nbMon[nbName];
  if(!p2p)return;
  m.queue=DynamicCast<DropTailQueue<Packet>>(p2p->GetQueue());m.lastBytes=m.queue?m.queue->GetTotalReceivedBytes():0;
}
void SatRouter::StartApplication(){
  m_n2sk=Socket::CreateSocket(GetNode(),UdpSocketFactory::GetTypeId());m_n2sk->Bind(InetSocketAddress(Ipv4Address("127.0.0.1"),9998));m_n2sk->SetRecvCallback(MakeCallback(&SatRouter::RecvN2,this));
  m_sk=Socket::CreateSocket(GetNode(),UdpSocketFactory::GetTypeId());m_sk->Bind(InetSocketAddress(Ipv4Address::GetAny(),9997));m_sk->SetRecvCallback(MakeCallback(&SatRouter::RecvEx,this));
  Simulator::Schedule(Seconds(0.05),&SatRouter::SendRequest,this);m_ct=Simulator::Schedule(Seconds(0.20),&SatRouter::CheckPortChange,this);
}
void SatRouter::StopApplication(){Simulator::Cancel(m_ct);if(m_n2sk)m_n2sk->Close();if(m_sk)m_sk->Close();}
void SatRouter::RecvN2(Ptr<Socket>s){Ptr<Packet>pkt;Address from;while((pkt=s->RecvFrom(from))){uint8_t buf[512];int pos=0;buf[pos++]=(uint8_t)m_gs.size();for(auto&p:m_gs){int32_t bw=(int32_t)p.second;memcpy(buf+pos,&bw,4);pos+=4;uint32_t nl=p.first.size();memcpy(buf+pos,&nl,4);pos+=4;memcpy(buf+pos,p.first.c_str(),nl);pos+=nl;std::string bl=Names::FindName(GetNode())+"→"+p.first+"("+std::to_string((int)p.second)+"M)";uint32_t blen=bl.size();memcpy(buf+pos,&blen,4);pos+=4;memcpy(buf+pos,bl.c_str(),blen);pos+=blen;}s->SendTo(Create<Packet>(buf,pos),0,from);}}
void SatRouter::SendPush(){if(m_gs.empty())return;std::string my=Names::FindName(GetNode());uint8_t buf[512];int p=0;buf[p++]=0x42;buf[p++]=0x32;buf[p++]=1;buf[p++]=0;p+=2;uint16_t seq=m_seq++;memcpy(buf+p,&seq,2);p+=2;buf[p++]=(uint8_t)my.size();memcpy(buf+p,my.c_str(),my.size());p+=my.size();int n=0;for(auto&x:m_gs)n++;buf[p++]=(uint8_t)n;for(auto&x:m_gs){uint8_t l=x.first.size();buf[p++]=l;memcpy(buf+p,x.first.c_str(),l);p+=l;int32_t bw=(int32_t)x.second;memcpy(buf+p,&bw,4);p+=4;}uint16_t total=(uint16_t)p;memcpy(buf+4,&total,2);Ptr<Packet>pkt=Create<Packet>(buf,p);for(auto&nb:m_nb)m_sk->SendTo(pkt,0,InetSocketAddress(nb.second.ip,9997));m_nbSnapshot.clear();for(auto&nb:m_nb)m_nbSnapshot[nb.first]=nb.second.bw;}
void SatRouter::SendRequest(){std::string my=Names::FindName(GetNode());uint8_t buf[256];int p=0;buf[p++]=0x42;buf[p++]=0x32;buf[p++]=1;buf[p++]=1;p+=2;uint16_t seq=m_seq++;memcpy(buf+p,&seq,2);p+=2;buf[p++]=(uint8_t)my.size();memcpy(buf+p,my.c_str(),my.size());p+=my.size();uint16_t total=(uint16_t)p;memcpy(buf+4,&total,2);Ptr<Packet>pkt=Create<Packet>(buf,p);for(auto&nb:m_nb)m_sk->SendTo(pkt,0,InetSocketAddress(nb.second.ip,9997));}
void SatRouter::SendReply(const std::string&tgt){if(m_gs.empty()||!m_nb.count(tgt))return;std::string my=Names::FindName(GetNode());uint8_t buf[512];int p=0;buf[p++]=0x42;buf[p++]=0x32;buf[p++]=1;buf[p++]=2;p+=2;uint16_t seq=m_seq++;memcpy(buf+p,&seq,2);p+=2;buf[p++]=(uint8_t)my.size();memcpy(buf+p,my.c_str(),my.size());p+=my.size();int n=0;for(auto&x:m_gs)n++;buf[p++]=(uint8_t)n;for(auto&x:m_gs){uint8_t l=x.first.size();buf[p++]=l;memcpy(buf+p,x.first.c_str(),l);p+=l;int32_t bw=(int32_t)x.second;memcpy(buf+p,&bw,4);p+=4;}uint16_t total=(uint16_t)p;memcpy(buf+4,&total,2);Ptr<Packet>pkt=Create<Packet>(buf,p);m_sk->SendTo(pkt,0,InetSocketAddress(m_nb[tgt].ip,9997));}
void SatRouter::RecvEx(Ptr<Socket>s){Ptr<Packet>pkt;Address from;bool prop=false;while((pkt=s->RecvFrom(from))){uint8_t buf[512];pkt->CopyData(buf,pkt->GetSize());if(pkt->GetSize()<9)continue;if(buf[0]!=0x42||buf[1]!=0x32)continue;if(buf[2]!=1)continue;uint8_t type=buf[3];uint16_t seq;memcpy(&seq,buf+6,2);uint8_t nl=buf[8];std::string nb((char*)buf+9,nl);int pos=9+nl;double nbLink=1e9;if(m_nbMon.count(nb))nbLink=m_nbMon[nb].availBw;else if(m_nb.count(nb))nbLink=m_nb[nb].bw;if(type==1){SendReply(nb);}else if(type==0||type==2){if(pkt->GetSize()<(uint32_t)pos+1)continue;int n=buf[pos++];bool chg=false;for(int i=0;i<n&&pos<(int)pkt->GetSize();i++){uint8_t gl=buf[pos++];std::string gs((char*)buf+pos,gl);pos+=gl;int32_t nbBw;memcpy(&nbBw,buf+pos,4);pos+=4;if(!m_nexthop.count(gs))continue;if(m_nexthop[gs]=="")continue;if(m_nexthop[gs]!=nb)continue;double newBw=std::min(nbLink,(double)nbBw);if(!m_gs.count(gs)||newBw!=m_gs[gs]){m_gs[gs]=newBw;chg=true;}}if(chg){m_bestBw=0;for(auto&p:m_gs)if(p.second>m_bestBw){m_bestBw=p.second;m_bestGs=p.first;}prop=true;}}}if(prop)SendPush();}
void SatRouter::CheckPortChange(){std::string my=Names::FindName(GetNode());double now=Simulator::Now().GetSeconds();double dt=(m_lastMonTime>0)?(now-m_lastMonTime):0.2;if(dt<0.01)dt=0.2;m_lastMonTime=now;for(auto&kv:m_nbMon){if(!kv.second.queue)continue;uint64_t cur=kv.second.queue->GetTotalReceivedBytes();uint64_t delta=cur-kv.second.lastBytes;double tputMbps=(delta*8.0/1e6)/dt;double cap=m_gsDirect.count(kv.first)?m_gsDirect[kv.first]:(m_nb.count(kv.first)?m_nb[kv.first].bw:1e9);kv.second.availBw=cap-tputMbps;if(kv.second.availBw<0)kv.second.availBw=0;kv.second.lastBytes=cur;}for(auto&gs:m_gsDirect){if(m_nbMon.count(gs.first))m_gs[gs.first]=m_nbMon[gs.first].availBw;}if(!m_init&&!m_gs.empty()){m_init=true;m_nbSnapshot.clear();for(auto&nb:m_nb)m_nbSnapshot[nb.first]=nb.second.bw;}else if(m_init){bool chg=false;if(m_nb.size()!=m_nbSnapshot.size())chg=true;else{for(auto&nb:m_nb)if(!m_nbSnapshot.count(nb.first)||std::abs(m_nbSnapshot[nb.first]-nb.second.bw)>0.5){chg=true;break;}}if(chg){for(auto&nb:m_nb){double old=m_nbSnapshot.count(nb.first)?m_nbSnapshot[nb.first]:0;if(std::abs(nb.second.bw-old)>0.5||old==0){for(auto&gs:m_nexthop)if(gs.second==nb.first)m_gs[gs.first]=0;}}SendPush();m_nbSnapshot.clear();for(auto&nb:m_nb)m_nbSnapshot[nb.first]=nb.second.bw;}}m_bestBw=0;for(auto&p:m_gs)if(p.second>m_bestBw){m_bestBw=p.second;m_bestGs=p.first;}m_ct=Simulator::Schedule(Seconds(0.20),&SatRouter::CheckPortChange,this);}

// ═══════════ gNB + UsrApp (minimal) ═══════════
class GnbApp:public Application{public:
  static TypeId GetTypeId();GnbApp(){}void AddCov(Ipv4Address ua){m_cov.push_back(ua);}void SetR(Ptr<SatRouter>r){m_r=r;}void Push();
private:virtual void StartApplication()override;virtual void StopApplication()override;void AutoPush();
  Ptr<Socket>m_sk;std::vector<Ipv4Address>m_cov;Ptr<SatRouter>m_r;uint16_t m_seq=0;EventId m_ap;
};
NS_OBJECT_ENSURE_REGISTERED(GnbApp);
TypeId GnbApp::GetTypeId(){static TypeId tid=TypeId("ns3::GnbApp").SetParent<Application>().SetGroupName("Sbdp").AddConstructor<GnbApp>();return tid;}
void GnbApp::StartApplication(){m_sk=Socket::CreateSocket(GetNode(),UdpSocketFactory::GetTypeId());m_sk->Bind(InetSocketAddress(Ipv4Address::GetAny(),9999));m_ap=Simulator::Schedule(Seconds(0.3),&GnbApp::AutoPush,this);}
void GnbApp::StopApplication(){Simulator::Cancel(m_ap);if(m_sk)m_sk->Close();}
void GnbApp::AutoPush(){Push();m_ap=Simulator::Schedule(Seconds(1.0),&GnbApp::AutoPush,this);}
void GnbApp::Push(){if(!m_r)return;double bw=m_r->GetBestE2e();std::string gs=m_r->GetBestGs();m_seq++;for(auto&ua:m_cov){SbdpHeader h=SbdpHeader::BuildAdv(Names::FindName(GetNode()),"UE",bw,Names::FindName(GetNode())+"→"+gs,m_seq);Ptr<Packet>p=Create<Packet>(0);p->AddHeader(h);m_sk->SendTo(p,0,InetSocketAddress(ua,8888));}NS_LOG_UNCOND("  [ADV "<<Names::FindName(GetNode())<<"@"<<Simulator::Now().GetSeconds()<<"s] bw="<<bw<<"M to "<<gs);}

class UsrApp:public Application{public:
  static TypeId GetTypeId();UsrApp(){}std::map<std::string,float>m_map;std::string m_cur;int m_ho=0;
private:virtual void StartApplication()override{m_sk=Socket::CreateSocket(GetNode(),UdpSocketFactory::GetTypeId());m_sk->Bind(InetSocketAddress(Ipv4Address::GetAny(),8888));m_sk->SetRecvCallback(MakeCallback(&UsrApp::Recv,this));}virtual void StopApplication()override{if(m_sk)m_sk->Close();}
  void Recv(Ptr<Socket>s){Ptr<Packet>pkt;Address from;while((pkt=s->RecvFrom(from))){SbdpHeader h;if(pkt->GetSize()>=SbdpHeader::SBDP_FIXED_SIZE){pkt->RemoveHeader(h);std::string sn=h.GetSrcNode();m_map[sn]=h.GetBackhaulBw();if(m_cur.empty())m_cur=sn;}}}
  Ptr<Socket>m_sk;
};
NS_OBJECT_ENSURE_REGISTERED(UsrApp);
TypeId UsrApp::GetTypeId(){static TypeId tid=TypeId("ns3::UsrApp").SetParent<Application>().SetGroupName("Sbdp").AddConstructor<UsrApp>();return tid;}

// ═══════════ Orbit topology events — hardcoded from orbit-events.py ═══════════
struct Edge { int a,b; double bw; };
struct OrbitEvent { double t; std::string desc; std::vector<Edge> edges; };
std::vector<OrbitEvent> orbitEvents = {
  {0, "INITIAL", {{1,2,200},{2,3,200},{3,1,200},{4,5,200},{5,6,200},{6,4,200},{2,4,180},{7,2,350}}},
  {20, "LOST GS-E feeder", {{1,2,200},{2,3,200},{3,1,200},{4,5,200},{5,6,200},{6,4,200},{2,4,180}}},
  {330, "INTER-PLANE change", {{1,2,200},{2,3,200},{3,1,200},{4,5,200},{5,6,200},{6,4,200},{1,5,180},{3,4,180},{7,3,350}}},
  {830, "FINAL", {{1,2,200},{2,3,200},{3,1,200},{4,5,200},{5,6,200},{6,4,200},{2,4,180},{7,1,350}}},
};

int main(int argc,char*argv[]){
  NodeContainer n;n.Create(10);
  Names::Add("A1",n.Get(0));Names::Add("A2",n.Get(1));Names::Add("A3",n.Get(2));
  Names::Add("B1",n.Get(3));Names::Add("B2",n.Get(4));Names::Add("B3",n.Get(5));
  Names::Add("GS-E",n.Get(6));Names::Add("GS-W",n.Get(7));
  Names::Add("U1",n.Get(8));Names::Add("Srv",n.Get(9));
  InternetStackHelper inet;inet.Install(n);
  PointToPointHelper p2p;p2p.SetQueue("ns3::DropTailQueue");Ipv4AddressHelper ipv4;uint32_t sn=0;

  // Pre-build ALL possible links from all events
  std::set<std::pair<int,int>> allLinks;
  for(auto&ev:orbitEvents)for(auto&e:ev.edges){int a=e.a-1,b=e.b-1;allLinks.insert({a<b?a:b,a<b?b:a});}
  allLinks.insert({8,0});allLinks.insert({8,1});allLinks.insert({6,9});  // user+server links
  std::map<std::pair<int,int>,NetDeviceContainer> linkDevs;
  auto buildLink=[&](int a,int b){auto k=std::make_pair(a<b?a:b,a<b?b:a);if(linkDevs.count(k))return;p2p.SetDeviceAttribute("DataRate",StringValue("1000Mbps"));p2p.SetChannelAttribute("Delay",StringValue("5ms"));auto dev=p2p.Install(n.Get(a),n.Get(b));linkDevs[k]=dev;char base[32];snprintf(base,32,"10.%u.0.0",sn++);ipv4.SetBase(base,"255.255.255.0");ipv4.Assign(dev);};
  for(auto&p:allLinks)buildLink(p.first,p.second);
  Ipv4GlobalRoutingHelper::PopulateRoutingTables();
  auto ip=[&](int i)->Ipv4Address{return n.Get(i)->GetObject<Ipv4>()->GetAddress(1,0).GetLocal();};
  auto setL=[&](std::pair<int,int>key,double bwMbps){if(!linkDevs.count(key))return;double bps=bwMbps*1e6;auto d0=DynamicCast<PointToPointNetDevice>(linkDevs[key].Get(0));auto d1=DynamicCast<PointToPointNetDevice>(linkDevs[key].Get(1));if(d0)d0->SetDataRate(DataRate(bps));if(d1)d1->SetDataRate(DataRate(bps));};

  // SatRouters
  struct Sat{Ptr<SatRouter>r;Ptr<GnbApp>g;};std::vector<Sat>sats(6);
  for(int i=0;i<6;i++){sats[i].r=CreateObject<SatRouter>();sats[i].g=CreateObject<GnbApp>();sats[i].g->SetR(sats[i].r);n.Get(i)->AddApplication(sats[i].r);sats[i].r->SetStartTime(Seconds(0));n.Get(i)->AddApplication(sats[i].g);sats[i].g->SetStartTime(Seconds(0.05));}

  // Initial topology
  auto applyTopo=[&](const OrbitEvent&ev){
    for(int i=0;i<6;i++){sats[i].r->m_nb.clear();sats[i].r->m_gs.clear();sats[i].r->m_nexthop.clear();}
    // Disable all ISL+GS links
    for(auto&kv:linkDevs){int a=kv.first.first,b=kv.first.second;if((a<6&&b<6)||(a==6||a==7||b==6||b==7)){auto&d=kv.second;auto dev0=DynamicCast<PointToPointNetDevice>(d.Get(0));auto dev1=DynamicCast<PointToPointNetDevice>(d.Get(1));if(dev0)dev0->SetDataRate(DataRate(0));if(dev1)dev1->SetDataRate(DataRate(0));}}
    // Enable edges from event
    for(auto&e:ev.edges){int a=e.a-1,b=e.b-1;setL({a<b?a:b,a<b?b:a},e.bw);if(a<6&&b<6){std::string na=Names::FindName(n.Get(a)),nb=Names::FindName(n.Get(b));sats[a].r->AddNb(nb,ip(b),e.bw);sats[b].r->AddNb(na,ip(a),e.bw);}if(a==6&&b<6){sats[b].r->AddDirectGs("GS-E",e.bw);sats[b].r->SetRoute("GS-E","");}if(b==6&&a<6){sats[a].r->AddDirectGs("GS-E",e.bw);sats[a].r->SetRoute("GS-E","");}if(a==7&&b<6){sats[b].r->AddDirectGs("GS-W",e.bw);sats[b].r->SetRoute("GS-W","");}if(b==7&&a<6){sats[a].r->AddDirectGs("GS-W",e.bw);sats[a].r->SetRoute("GS-W","");}}
    Ipv4GlobalRoutingHelper::RecomputeRoutingTables();
    // Compute nexthop routes
    for(int i=0;i<6;i++){for(auto&gs:std::map<std::string,int>{{"GS-E",6},{"GS-W",7}}){Ipv4Header hdr;hdr.SetDestination(ip(gs.second));hdr.SetProtocol(17);Socket::SocketErrno se;Ptr<Ipv4Route> rt=n.Get(i)->GetObject<Ipv4>()->GetRoutingProtocol()->RouteOutput(Create<Packet>(),hdr,Ptr<NetDevice>(),se);if(rt){std::string nh="";Ipv4Address gw=rt->GetGateway();for(auto&nb:sats[i].r->m_nb)if(nb.second.ip==gw)nh=nb.first;sats[i].r->SetRoute(gs.first,nh);}}}
    for(int i=0;i<6;i++)sats[i].r->UpdateBest();
  };

  // Install monitors for all ISL+GS links
  for(auto&kv:linkDevs){int a=kv.first.first,b=kv.first.second;if(a<6&&b<6){sats[a].r->InstallMonitor(Names::FindName(n.Get(b)),kv.second.Get(a<b?0:1));sats[b].r->InstallMonitor(Names::FindName(n.Get(a)),kv.second.Get(a<b?1:0));}if(a==6&&b<6)sats[b].r->InstallMonitor("GS-E",kv.second.Get(1));if(b==6&&a<6)sats[a].r->InstallMonitor("GS-E",kv.second.Get(0));}

  applyTopo(orbitEvents[0]);
  for(int i=0;i<6;i++){sats[i].g->AddCov(ip(8));}

  Ptr<UsrApp> u1=CreateObject<UsrApp>();n.Get(8)->AddApplication(u1);u1->SetStartTime(Seconds(0.05));

  // Data flow: U1→GS-E, 100Mbps UDP
  Ipv4Address gsIp=ip(6);std::vector<Ptr<PacketSink>>sinks;
  PacketSinkHelper sk("ns3::UdpSocketFactory",InetSocketAddress(Ipv4Address::GetAny(),5001));
  auto sink=sk.Install(n.Get(6));sink.Start(Seconds(0.3));sink.Stop(Seconds(900));sinks.push_back(DynamicCast<PacketSink>(sink.Get(0)));
  OnOffHelper oo("ns3::UdpSocketFactory",InetSocketAddress(gsIp,5001));oo.SetAttribute("DataRate",DataRateValue(DataRate("100Mbps")));oo.SetAttribute("PacketSize",UintegerValue(1472));oo.SetConstantRate(DataRate("100Mbps"));
  auto src=oo.Install(n.Get(8));src.Start(Seconds(0.5));src.Stop(Seconds(900));

  // Schedule topology events
  for(size_t i=1;i<orbitEvents.size();i++){auto ev=orbitEvents[i];Simulator::Schedule(Seconds(ev.t),[=](){NS_LOG_UNCOND("\n═══ t="<<(int)ev.t<<"s "<<ev.desc<<" ═══");applyTopo(ev);});}

  // Report
  Simulator::Schedule(Seconds(895),[&](){NS_LOG_UNCOND("\n═══ Exp 3 Report ═══");double mb=sinks[0]->GetTotalRx()/1e6;NS_LOG_UNCOND("  U1: "<<u1->m_map.size()<<" sats | data:"<<mb<<"MB");for(int i=0;i<6;i++)NS_LOG_UNCOND("  "<<Names::FindName(n.Get(i))<<" B2="<<sats[i].r->GetBestE2e()<<"M to "<<sats[i].r->GetBestGs());});

  NS_LOG_UNCOND("\n═══ Exp 3: Dynamic Orbit B2 ═══\n");Simulator::Stop(Seconds(900));Simulator::Run();Simulator::Destroy();return 0;
}